select * from Strutture;
insert into Strutture values ('Paestum','Salerno',0,20,'8:00-13:00','Cultura',40.25885,15.01953,"Paestum, nota anche come Pesto, è un'antica città della Magna Grecia chiamata dai fondatori Poseidonia in onore di Poseidone, ma devotissima ad Atena ed Era. Dopo la sua conquista da parte dei Lucani venne chiamata Paistom, per poi assumere, sotto i romani, il nome di Paestum. L'estensione del suo abitato è ancora oggi ben riconoscibile, racchiuso dalle sue mura greche, così come modificate in epoca lucana e poi romana.");
insert into Strutture values ('Grand Hotel Salerno','Salerno',0,1600,'9:00-15:00','Hotel',40.6724433898926,14.7758684158325,"Affacciato sul Golfo di Salerno, questo hotel elegante dista 3,1 km dalla Cattedrale di Salerno e 4,8 km dai musei del Castello di Arechi.
Le camere eleganti sono dotate di minibar, WiFi gratuito e TV a schermo piatto. Le sistemazioni di categoria superiore includono un balcone con vista sul mare e, in alcuni casi, un secondo bagno. Le suite offrono in più un'area soggiorno. È disponibile il servizio in camera.");
insert into Strutture values ('Castello di Arechi','Salerno',0,10,'8:00-13:00','Cultura',40.4103,14.4518,"Il Castello di Arechi è un castello medievale, situato ad un'altezza di circa 300 metri sul livello del mare, che domina la città ed il golfo di Salerno. È detto di Arechi perché la costruzione di questa fortificazione si associa, tradizionalmente, al duca longobardo Arechi II.");
insert into Strutture values ('Cattedrale di Salerno','Salerno',0,'Gratuito','8:00-13:00','Cultura',40.680362, 14.759865,"Ricercata chiesa del 1084 circa con grande campanile, organo a canne, mosaici, statue e reliquie.");
insert into Strutture values ('Terminal Frutta Salerno Srl','Salerno',0,'Gratuito','9:00-15:00','Negozio',40.674520, 14.741690,"Più grande mercato all'ingrosso di fruttivendolo della campania");
insert into Strutture values ('Reggia di Caserta','Caserta',0,'Gratuito','8:00-13:00','Museo',41.072337, 14.327068,"Imponente reggia barocca con un ampio parco decorato da fontane, teatro di corte e visite guidate.");
insert into Strutture values ('Il giardino Inglese','Caserta',0,'Gratuito','8:00-13:00','Cultura',41.098029, 14.332198,"Reggia con giardino all'inglese del '700 che contiene piante rare, statue di marmo e resti dell'antica Pompei.");
insert into Strutture values ('Ristorante Pepe Nero','Caserta',0,200,'18:00-00:00','Ristorante',41.080949, 14.332054,"Pizze e specialità mediterranee in un ristorante curato con pareti bianche e rosse decorate da cornici.");
insert into Strutture values ('Pacifico Libri','Caserta',0,100,'9:00-15:00','Negozio',41.075012, 14.337550,"Una libreria è un negozio adibito alla vendita di libri, periodici e altri materiali informativi, organizzati secondo criteri utili a favorirne la ricerca da parte del cliente. Oltre a svolgere la funzione di consigliare il cliente, una libreria offre una scelta delle novità e delle riedizioni librarie disponibili sul mercato.");
insert into Strutture values ('Amici di Hackert','Caserta',0,95,'8:00-13:00','Hotel',41.086094, 14.338294,"Nel nostro piccolo albergo tutti sono i benvenuti");
insert into Strutture values ('Villa Comunale','Castellamare di Stabia',0,'Gratuito','18:00-00:00','Cultura',40.699904, 14.481579,"Villa aperta al pubblico, restaurata nel 2009");
insert into Strutture values ('Scavi archeologici di Stabia','Castellamare di Stabia',0,10,'8:00-13:00','Museo',40.703598, 14.500263,"Sito archeologico romano con ville, reperti e affreschi di una città sepolta durante l'eruzione del 79 d.C.");
insert into Strutture values (
insert into Strutture values (
insert into Strutture value("Anfiteatro Flavio","Pozzuoli",3.5,25,"8:00-13:00","Museo","40.825869","14.125078","L'Anfiteatro Flavio è uno dei due anfiteatri romani esistenti a Pozzuoli e risale alla seconda metà del I secolo d.C. Venne realizzato per far fronte all'incremento demografico di Puteoli, che aveva reso inadatto il vecchio edificio adibito per spettacoli pubblici in età repubblicana. Secondo solo al Colosseo e all'anfiteatro Campano in quanto capacità di capienza, sorge in concomitanza della convergenza di due vie principali, la Via Domitiana e la via per Napoli");
insert into Strutture value("Pompei","Pompei",2.9,"20","8:00-13:00","Museo","40.749183654785156","14.500738143920898","Pompei (in latino: Pompeii) è una città dell'evo antico, corrispondente all'attuale Pompei, la cui storia ha origine dal IX secolo a.C. per terminare nel 79, quando, a seguito dell'eruzione del Vesuvio, viene ricoperta sotto una coltre di ceneri e lapilli alta circa sei metri. La sua riscoperta e i relativi scavi, iniziati nel 1748, hanno riportato alla luce un sito archeologico che nel 1997 è entrato a far parte della lista dei patrimoni dell'umanità dell'UNESCO, e che è il secondo monumento italiano per visite dopo il sistema museale del Colosseo, Foro Romano e Palatino[");
insert into Strutture value("Piazza del Plebiscito","Napoli",3.5,"Gratuito","9:00-15:00","Cultura","40.835896","14.248784","Piazza del Plebiscito (già largo di Palazzo o Foro Regio) è una piazza di Napoli posizionata al termine di via Toledo, non appena oltrepassata piazza Trieste e Trento.Ubicata nel centro storico, tra il lungomare e via Toledo, con una superficie di circa 25 000 metri quadrati la piazza si presenta come una delle più grandi della città e d'Italia e per questo è quella più utilizzata per le grandi manifestazioni.");
insert into Strutture value("Teatro San Carlo","Napoli",5.0,"120","12:00-18:00","Intrattenimento","40.85299","14.24789","Il Teatro di San Carlo, noto semplicemente come Teatro San Carlo, è un teatro lirico di Napoli, tra i più famosi e prestigiosi al mondo, fondato nel 1737.[1] Può ospitare 1386 spettatori[2] e conta una vasta platea (22×28×23 m), cinque ordini di palchi disposti a ferro di cavallo più un ampio palco reale, un loggione ed un palcoscenico (34×33 m).[3][4] Date le sue dimensioni, struttura e antichità è stato modello per i successivi teatri d'Europa.");
insert into Strutture value("Castel dell'Ovo","Napoli",4.9,"Gratuito","9:00-15:00","Cultura","40.827222","14.248611","Il castel dell'Ovo (castrum Ovi, in latino), è il castello più antico della città di Napoli[1] ed è uno degli elementi che spiccano maggiormente nel celebre panorama del golfo. Si trova tra i quartieri di San Ferdinando e Chiaia, di fronte a via Partenope. A causa di diversi eventi che hanno in parte distrutto l'originario aspetto normanno e grazie ai successivi lavori di ricostruzione avvenuti durante il periodo angioino ed aragonese, la linea architettonica del castello mutò drasticamente fino a giungere allo stato in cui si presenta oggi.");
delete from Strutture;
drop table Strutture;

CREATE TABLE `Strutture` (
  `nome` varchar(50) NOT NULL,
  `città` varchar(30) NOT NULL,
  `valutazioneMedia` varchar(3) DEFAULT NULL,
  `maxPrezzo` varchar(10) DEFAULT NULL,
  `orarioApertura` varchar(15) DEFAULT NULL,
  `categoria` varchar(15) DEFAULT NULL,
  `latitudine` varchar(30) NOT NULL,
  `longitudine` varchar(30) NOT NULL,
  `descrizione` varchar(1500) DEFAULT NULL,
  PRIMARY KEY (`nome`,`latitudine`,`longitudine`)
)